env: test
paths:
  input_base_dir: data/input/test
  input_dir: data/input/test
  output_base_dir: data/output/test
  output_dir: data/output/test
postgresql:
  host: bi-idi.cluster-cvq28ma6cvue.eu-west-1.rds.amazonaws.com
  port: 5432
  database: data_dbo_idi
  user: bi_admin
  schema: test
